// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./audio.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.SINT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.PACKED;

public final class AudioPlayList extends Message {

  public static final Long DEFAULT_ID = 0L;
  public static final String DEFAULT_NAME = "";
  public static final List<Long> DEFAULT_TRACKS = Collections.emptyList();
  public static final Long DEFAULT_DATE_ADDED = 0L;
  public static final Long DEFAULT_DATE_MODIFIED = 0L;

  @ProtoField(tag = 1, type = SINT64)
  public final Long id;

  @ProtoField(tag = 2, type = STRING)
  public final String name;

  @ProtoField(tag = 3, type = SINT64, label = PACKED)
  public final List<Long> tracks;

  @ProtoField(tag = 4, type = INT64)
  public final Long date_added;

  @ProtoField(tag = 5, type = INT64)
  public final Long date_modified;

  private AudioPlayList(Builder builder) {
    super(builder);
    this.id = builder.id;
    this.name = builder.name;
    this.tracks = immutableCopyOf(builder.tracks);
    this.date_added = builder.date_added;
    this.date_modified = builder.date_modified;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AudioPlayList)) return false;
    AudioPlayList o = (AudioPlayList) other;
    return equals(id, o.id)
        && equals(name, o.name)
        && equals(tracks, o.tracks)
        && equals(date_added, o.date_added)
        && equals(date_modified, o.date_modified);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = id != null ? id.hashCode() : 0;
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (tracks != null ? tracks.hashCode() : 1);
      result = result * 37 + (date_added != null ? date_added.hashCode() : 0);
      result = result * 37 + (date_modified != null ? date_modified.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<AudioPlayList> {

    public Long id;
    public String name;
    public List<Long> tracks;
    public Long date_added;
    public Long date_modified;

    public Builder() {
    }

    public Builder(AudioPlayList message) {
      super(message);
      if (message == null) return;
      this.id = message.id;
      this.name = message.name;
      this.tracks = copyOf(message.tracks);
      this.date_added = message.date_added;
      this.date_modified = message.date_modified;
    }

    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder tracks(List<Long> tracks) {
      this.tracks = checkForNulls(tracks);
      return this;
    }

    public Builder date_added(Long date_added) {
      this.date_added = date_added;
      return this;
    }

    public Builder date_modified(Long date_modified) {
      this.date_modified = date_modified;
      return this;
    }

    @Override
    public AudioPlayList build() {
      return new AudioPlayList(this);
    }
  }
}
