// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./audio.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class AudioPlayLists extends Message {

  public static final List<AudioPlayList> DEFAULT_PLAYLIST = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<AudioPlayList> playList;

  private AudioPlayLists(Builder builder) {
    super(builder);
    this.playList = immutableCopyOf(builder.playList);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AudioPlayLists)) return false;
    return equals(playList, ((AudioPlayLists) other).playList);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = playList != null ? playList.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<AudioPlayLists> {

    public List<AudioPlayList> playList;

    public Builder() {
    }

    public Builder(AudioPlayLists message) {
      super(message);
      if (message == null) return;
      this.playList = copyOf(message.playList);
    }

    public Builder playList(List<AudioPlayList> playList) {
      this.playList = checkForNulls(playList);
      return this;
    }

    @Override
    public AudioPlayLists build() {
      return new AudioPlayLists(this);
    }
  }
}
