// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./audio.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class AudioAlbums extends Message {

  public static final List<AudioAlbum> DEFAULT_ALBUM = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<AudioAlbum> album;

  private AudioAlbums(Builder builder) {
    super(builder);
    this.album = immutableCopyOf(builder.album);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AudioAlbums)) return false;
    return equals(album, ((AudioAlbums) other).album);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = album != null ? album.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<AudioAlbums> {

    public List<AudioAlbum> album;

    public Builder() {
    }

    public Builder(AudioAlbums message) {
      super(message);
      if (message == null) return;
      this.album = copyOf(message.album);
    }

    public Builder album(List<AudioAlbum> album) {
      this.album = checkForNulls(album);
      return this;
    }

    @Override
    public AudioAlbums build() {
      return new AudioAlbums(this);
    }
  }
}
