// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./audio.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class AudioArtists extends Message {

  public static final List<AudioArtist> DEFAULT_ARTIST = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<AudioArtist> artist;

  private AudioArtists(Builder builder) {
    super(builder);
    this.artist = immutableCopyOf(builder.artist);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AudioArtists)) return false;
    return equals(artist, ((AudioArtists) other).artist);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = artist != null ? artist.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<AudioArtists> {

    public List<AudioArtist> artist;

    public Builder() {
    }

    public Builder(AudioArtists message) {
      super(message);
      if (message == null) return;
      this.artist = copyOf(message.artist);
    }

    public Builder artist(List<AudioArtist> artist) {
      this.artist = checkForNulls(artist);
      return this;
    }

    @Override
    public AudioArtists build() {
      return new AudioArtists(this);
    }
  }
}
