// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./audio.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class MediaAudios extends Message {

  public static final List<MediaAudio> DEFAULT_AUDIO = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<MediaAudio> audio;

  private MediaAudios(Builder builder) {
    super(builder);
    this.audio = immutableCopyOf(builder.audio);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MediaAudios)) return false;
    return equals(audio, ((MediaAudios) other).audio);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = audio != null ? audio.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<MediaAudios> {

    public List<MediaAudio> audio;

    public Builder() {
    }

    public Builder(MediaAudios message) {
      super(message);
      if (message == null) return;
      this.audio = copyOf(message.audio);
    }

    public Builder audio(List<MediaAudio> audio) {
      this.audio = checkForNulls(audio);
      return this;
    }

    @Override
    public MediaAudios build() {
      return new MediaAudios(this);
    }
  }
}
