// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./video.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class MediaVideos extends Message {

  public static final List<MediaVideo> DEFAULT_VIDEO = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<MediaVideo> video;

  private MediaVideos(Builder builder) {
    super(builder);
    this.video = immutableCopyOf(builder.video);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MediaVideos)) return false;
    return equals(video, ((MediaVideos) other).video);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = video != null ? video.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<MediaVideos> {

    public List<MediaVideo> video;

    public Builder() {
    }

    public Builder(MediaVideos message) {
      super(message);
      if (message == null) return;
      this.video = copyOf(message.video);
    }

    public Builder video(List<MediaVideo> video) {
      this.video = checkForNulls(video);
      return this;
    }

    @Override
    public MediaVideos build() {
      return new MediaVideos(this);
    }
  }
}
