// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./image.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class MediaImages extends Message {

  public static final List<MediaImage> DEFAULT_IMAGE = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<MediaImage> image;

  private MediaImages(Builder builder) {
    super(builder);
    this.image = immutableCopyOf(builder.image);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MediaImages)) return false;
    return equals(image, ((MediaImages) other).image);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = image != null ? image.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<MediaImages> {

    public List<MediaImage> image;

    public Builder() {
    }

    public Builder(MediaImages message) {
      super(message);
      if (message == null) return;
      this.image = copyOf(message.image);
    }

    public Builder image(List<MediaImage> image) {
      this.image = checkForNulls(image);
      return this;
    }

    @Override
    public MediaImages build() {
      return new MediaImages(this);
    }
  }
}
