// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./image.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class PhotoFolderInfo extends Message {

  public static final String DEFAULT_PATH = "";
  public static final String DEFAULT_NAME = "";

  @ProtoField(tag = 1, type = STRING)
  public final String path;

  @ProtoField(tag = 2, type = STRING)
  public final String name;

  private PhotoFolderInfo(Builder builder) {
    super(builder);
    this.path = builder.path;
    this.name = builder.name;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PhotoFolderInfo)) return false;
    PhotoFolderInfo o = (PhotoFolderInfo) other;
    return equals(path, o.path)
        && equals(name, o.name);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = path != null ? path.hashCode() : 0;
      result = result * 37 + (name != null ? name.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PhotoFolderInfo> {

    public String path;
    public String name;

    public Builder() {
    }

    public Builder(PhotoFolderInfo message) {
      super(message);
      if (message == null) return;
      this.path = message.path;
      this.name = message.name;
    }

    public Builder path(String path) {
      this.path = path;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    @Override
    public PhotoFolderInfo build() {
      return new PhotoFolderInfo(this);
    }
  }
}
