// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./image.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class PhotoFolderInfos extends Message {

  public static final List<PhotoFolderInfo> DEFAULT_PHOTO_FOLDER_INFO = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<PhotoFolderInfo> photo_folder_info;

  private PhotoFolderInfos(Builder builder) {
    super(builder);
    this.photo_folder_info = immutableCopyOf(builder.photo_folder_info);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PhotoFolderInfos)) return false;
    return equals(photo_folder_info, ((PhotoFolderInfos) other).photo_folder_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = photo_folder_info != null ? photo_folder_info.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<PhotoFolderInfos> {

    public List<PhotoFolderInfo> photo_folder_info;

    public Builder() {
    }

    public Builder(PhotoFolderInfos message) {
      super(message);
      if (message == null) return;
      this.photo_folder_info = copyOf(message.photo_folder_info);
    }

    public Builder photo_folder_info(List<PhotoFolderInfo> photo_folder_info) {
      this.photo_folder_info = checkForNulls(photo_folder_info);
      return this;
    }

    @Override
    public PhotoFolderInfos build() {
      return new PhotoFolderInfos(this);
    }
  }
}
