// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./thumbnail.proto
package com.wandoujia.media.pmp.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;

public final class ThumbnailItem extends Message {

  public static final Long DEFAULT_IMAGE_ID = 0L;

  @ProtoField(tag = 1, type = INT64)
  public final Long image_id;

  @ProtoField(tag = 2)
  public final Thumbnail thumbnail;

  private ThumbnailItem(Builder builder) {
    super(builder);
    this.image_id = builder.image_id;
    this.thumbnail = builder.thumbnail;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ThumbnailItem)) return false;
    ThumbnailItem o = (ThumbnailItem) other;
    return equals(image_id, o.image_id)
        && equals(thumbnail, o.thumbnail);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = image_id != null ? image_id.hashCode() : 0;
      result = result * 37 + (thumbnail != null ? thumbnail.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ThumbnailItem> {

    public Long image_id;
    public Thumbnail thumbnail;

    public Builder() {
    }

    public Builder(ThumbnailItem message) {
      super(message);
      if (message == null) return;
      this.image_id = message.image_id;
      this.thumbnail = message.thumbnail;
    }

    public Builder image_id(Long image_id) {
      this.image_id = image_id;
      return this;
    }

    public Builder thumbnail(Thumbnail thumbnail) {
      this.thumbnail = thumbnail;
      return this;
    }

    @Override
    public ThumbnailItem build() {
      return new ThumbnailItem(this);
    }
  }
}
