// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_common_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 注册帐户信息
 */
public final class AccountPackage extends Message {

  public static final String DEFAULT_UID = "";

  /**
   * 注册帐号id
   */
  @ProtoField(tag = 1, type = STRING)
  public final String uid;

  private AccountPackage(Builder builder) {
    super(builder);
    this.uid = builder.uid;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AccountPackage)) return false;
    return equals(uid, ((AccountPackage) other).uid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = uid != null ? uid.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<AccountPackage> {

    public String uid;

    public Builder() {
    }

    public Builder(AccountPackage message) {
      super(message);
      if (message == null) return;
      this.uid = message.uid;
    }

    /**
     * 注册帐号id
     */
    public Builder uid(String uid) {
      this.uid = uid;
      return this;
    }

    @Override
    public AccountPackage build() {
      return new AccountPackage(this);
    }
  }
}
