// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_event_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 应用活跃
 */
public final class ApplicationActiveEvent extends Message {

  public static final String DEFAULT_ACTIVE = "";

  @ProtoField(tag = 1, type = STRING)
  public final String active;

  private ApplicationActiveEvent(Builder builder) {
    super(builder);
    this.active = builder.active;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ApplicationActiveEvent)) return false;
    return equals(active, ((ApplicationActiveEvent) other).active);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = active != null ? active.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<ApplicationActiveEvent> {

    public String active;

    public Builder() {
    }

    public Builder(ApplicationActiveEvent message) {
      super(message);
      if (message == null) return;
      this.active = message.active;
    }

    public Builder active(String active) {
      this.active = active;
      return this;
    }

    @Override
    public ApplicationActiveEvent build() {
      return new ApplicationActiveEvent(this);
    }
  }
}
