// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_event_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 应用启动
 */
public final class ApplicationStartEvent extends Message {

  public static final String DEFAULT_ACTION = "";
  public static final String DEFAULT_ACTIVITY = "";
  public static final String DEFAULT_DATA = "";
  public static final Reason DEFAULT_REASON = Reason.NEW;

  /**
   * intent的action
   */
  @ProtoField(tag = 1, type = STRING)
  public final String action;

  /**
   * intent进入的activity name
   */
  @ProtoField(tag = 2, type = STRING)
  public final String activity;

  /**
   * intent的data
   */
  @ProtoField(tag = 3, type = STRING)
  public final String data;

  /**
   * new, reload, restart to foreground
   */
  @ProtoField(tag = 4, type = ENUM)
  public final Reason reason;

  private ApplicationStartEvent(Builder builder) {
    super(builder);
    this.action = builder.action;
    this.activity = builder.activity;
    this.data = builder.data;
    this.reason = builder.reason;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ApplicationStartEvent)) return false;
    ApplicationStartEvent o = (ApplicationStartEvent) other;
    return equals(action, o.action)
        && equals(activity, o.activity)
        && equals(data, o.data)
        && equals(reason, o.reason);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = action != null ? action.hashCode() : 0;
      result = result * 37 + (activity != null ? activity.hashCode() : 0);
      result = result * 37 + (data != null ? data.hashCode() : 0);
      result = result * 37 + (reason != null ? reason.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ApplicationStartEvent> {

    public String action;
    public String activity;
    public String data;
    public Reason reason;

    public Builder() {
    }

    public Builder(ApplicationStartEvent message) {
      super(message);
      if (message == null) return;
      this.action = message.action;
      this.activity = message.activity;
      this.data = message.data;
      this.reason = message.reason;
    }

    /**
     * intent的action
     */
    public Builder action(String action) {
      this.action = action;
      return this;
    }

    /**
     * intent进入的activity name
     */
    public Builder activity(String activity) {
      this.activity = activity;
      return this;
    }

    /**
     * intent的data
     */
    public Builder data(String data) {
      this.data = data;
      return this;
    }

    /**
     * new, reload, restart to foreground
     */
    public Builder reason(Reason reason) {
      this.reason = reason;
      return this;
    }

    @Override
    public ApplicationStartEvent build() {
      return new ApplicationStartEvent(this);
    }
  }

  public enum Reason
      implements ProtoEnum {
    NEW(0),
    /**
     * 一次全新的启动
     */
    RELOAD(1),
    /**
     * 应用在打开状态刷新页面
     */
    RESTART(2);

    private final int value;

    private Reason(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
