// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_extra_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 应用状态信息
 */
public final class AppStatusPackage extends Message {

  public static final Boolean DEFAULT_IS_PREDOWNLOAD = false;
  public static final Boolean DEFAULT_IS_INSTALLED = false;
  public static final String DEFAULT_APP_VERSION_NAME = "";
  public static final Integer DEFAULT_APP_VERSION_CODE = 0;

  /**
   * 是否是预下载
   */
  @ProtoField(tag = 1, type = BOOL)
  public final Boolean is_predownload;

  /**
   * 是否已安装
   */
  @ProtoField(tag = 2, type = BOOL)
  public final Boolean is_installed;

  /**
   * 应用的版本名
   */
  @ProtoField(tag = 3, type = STRING)
  public final String app_version_name;

  /**
   * 应用的版本号
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer app_version_code;

  private AppStatusPackage(Builder builder) {
    super(builder);
    this.is_predownload = builder.is_predownload;
    this.is_installed = builder.is_installed;
    this.app_version_name = builder.app_version_name;
    this.app_version_code = builder.app_version_code;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AppStatusPackage)) return false;
    AppStatusPackage o = (AppStatusPackage) other;
    return equals(is_predownload, o.is_predownload)
        && equals(is_installed, o.is_installed)
        && equals(app_version_name, o.app_version_name)
        && equals(app_version_code, o.app_version_code);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = is_predownload != null ? is_predownload.hashCode() : 0;
      result = result * 37 + (is_installed != null ? is_installed.hashCode() : 0);
      result = result * 37 + (app_version_name != null ? app_version_name.hashCode() : 0);
      result = result * 37 + (app_version_code != null ? app_version_code.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<AppStatusPackage> {

    public Boolean is_predownload;
    public Boolean is_installed;
    public String app_version_name;
    public Integer app_version_code;

    public Builder() {
    }

    public Builder(AppStatusPackage message) {
      super(message);
      if (message == null) return;
      this.is_predownload = message.is_predownload;
      this.is_installed = message.is_installed;
      this.app_version_name = message.app_version_name;
      this.app_version_code = message.app_version_code;
    }

    /**
     * 是否是预下载
     */
    public Builder is_predownload(Boolean is_predownload) {
      this.is_predownload = is_predownload;
      return this;
    }

    /**
     * 是否已安装
     */
    public Builder is_installed(Boolean is_installed) {
      this.is_installed = is_installed;
      return this;
    }

    /**
     * 应用的版本名
     */
    public Builder app_version_name(String app_version_name) {
      this.app_version_name = app_version_name;
      return this;
    }

    /**
     * 应用的版本号
     */
    public Builder app_version_code(Integer app_version_code) {
      this.app_version_code = app_version_code;
      return this;
    }

    @Override
    public AppStatusPackage build() {
      return new AppStatusPackage(this);
    }
  }
}
