// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_event_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 消费
 */
public final class ConsumptionEvent extends Message {

  public static final Type DEFAULT_TYPE = Type.DOWNLOAD;
  public static final String DEFAULT_SOURCE = "";
  public static final Result DEFAULT_RESULT = Result.SUCCESS;

  /**
   * 消费方式
   */
  @ProtoField(tag = 1, type = ENUM)
  public final Type type;

  /**
   * 消费来源
   */
  @ProtoField(tag = 2, type = STRING)
  public final String source;

  /**
   * 消费结果
   */
  @ProtoField(tag = 3, type = ENUM)
  public final Result result;

  /**
   * 当前页面信息
   */
  @ProtoField(tag = 4)
  public final ViewLogPackage view;

  private ConsumptionEvent(Builder builder) {
    super(builder);
    this.type = builder.type;
    this.source = builder.source;
    this.result = builder.result;
    this.view = builder.view;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ConsumptionEvent)) return false;
    ConsumptionEvent o = (ConsumptionEvent) other;
    return equals(type, o.type)
        && equals(source, o.source)
        && equals(result, o.result)
        && equals(view, o.view);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = type != null ? type.hashCode() : 0;
      result = result * 37 + (source != null ? source.hashCode() : 0);
      result = result * 37 + (this.result != null ? this.result.hashCode() : 0);
      result = result * 37 + (view != null ? view.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ConsumptionEvent> {

    public Type type;
    public String source;
    public Result result;
    public ViewLogPackage view;

    public Builder() {
    }

    public Builder(ConsumptionEvent message) {
      super(message);
      if (message == null) return;
      this.type = message.type;
      this.source = message.source;
      this.result = message.result;
      this.view = message.view;
    }

    /**
     * 消费方式
     */
    public Builder type(Type type) {
      this.type = type;
      return this;
    }

    /**
     * 消费来源
     */
    public Builder source(String source) {
      this.source = source;
      return this;
    }

    /**
     * 消费结果
     */
    public Builder result(Result result) {
      this.result = result;
      return this;
    }

    /**
     * 当前页面信息
     */
    public Builder view(ViewLogPackage view) {
      this.view = view;
      return this;
    }

    @Override
    public ConsumptionEvent build() {
      return new ConsumptionEvent(this);
    }
  }

  public enum Type
      implements ProtoEnum {
    DOWNLOAD(0),
    /**
     * 下载
     */
    ONLINE_PLAY(1),
    /**
     * 在线播放
     */
    LOCAL_PLAY(2),
    /**
     * 本地播放
     */
    READ(3),
    /**
     * 阅读
     */
    SET_AS_WALLPAPER(4),
    /**
     * 设置壁纸
     */
    OPEN(5),
    /**
     * 打开
     */
    UPGRADE(6),
    /**
     * 升级
     */
    INSTALL(7),
    /**
     * 安装
     */
    UNINSTALL(8);

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }

  public enum Result
      implements ProtoEnum {
    SUCCESS(0),
    /**
     * 成功
     */
    FAILED(1);

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
