// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_extra_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

public final class ExtraPackage extends Message {

  /**
   * owner=
   */
  @ProtoField(tag = 1)
  public final CardPackage card_package;

  /**
   * owner=
   */
  @ProtoField(tag = 2)
  public final DevicePackage device_package;

  /**
   * owner=
   */
  @ProtoField(tag = 3)
  public final ContentPackage content_package;

  /**
   * owner=
   */
  @ProtoField(tag = 4)
  public final FeedPackage feed_package;

  /**
   * owner=zhaoqi
   */
  @ProtoField(tag = 5)
  public final ResourcePackage resource_package;

  /**
   * owner=
   */
  @ProtoField(tag = 6)
  public final OpenTypePackage open_type_package;

  /**
   * owner=
   */
  @ProtoField(tag = 7)
  public final AppStatusPackage app_status_package;

  private ExtraPackage(Builder builder) {
    super(builder);
    this.card_package = builder.card_package;
    this.device_package = builder.device_package;
    this.content_package = builder.content_package;
    this.feed_package = builder.feed_package;
    this.resource_package = builder.resource_package;
    this.open_type_package = builder.open_type_package;
    this.app_status_package = builder.app_status_package;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ExtraPackage)) return false;
    ExtraPackage o = (ExtraPackage) other;
    return equals(card_package, o.card_package)
        && equals(device_package, o.device_package)
        && equals(content_package, o.content_package)
        && equals(feed_package, o.feed_package)
        && equals(resource_package, o.resource_package)
        && equals(open_type_package, o.open_type_package)
        && equals(app_status_package, o.app_status_package);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = card_package != null ? card_package.hashCode() : 0;
      result = result * 37 + (device_package != null ? device_package.hashCode() : 0);
      result = result * 37 + (content_package != null ? content_package.hashCode() : 0);
      result = result * 37 + (feed_package != null ? feed_package.hashCode() : 0);
      result = result * 37 + (resource_package != null ? resource_package.hashCode() : 0);
      result = result * 37 + (open_type_package != null ? open_type_package.hashCode() : 0);
      result = result * 37 + (app_status_package != null ? app_status_package.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ExtraPackage> {

    public CardPackage card_package;
    public DevicePackage device_package;
    public ContentPackage content_package;
    public FeedPackage feed_package;
    public ResourcePackage resource_package;
    public OpenTypePackage open_type_package;
    public AppStatusPackage app_status_package;

    public Builder() {
    }

    public Builder(ExtraPackage message) {
      super(message);
      if (message == null) return;
      this.card_package = message.card_package;
      this.device_package = message.device_package;
      this.content_package = message.content_package;
      this.feed_package = message.feed_package;
      this.resource_package = message.resource_package;
      this.open_type_package = message.open_type_package;
      this.app_status_package = message.app_status_package;
    }

    /**
     * owner=
     */
    public Builder card_package(CardPackage card_package) {
      this.card_package = card_package;
      return this;
    }

    /**
     * owner=
     */
    public Builder device_package(DevicePackage device_package) {
      this.device_package = device_package;
      return this;
    }

    /**
     * owner=
     */
    public Builder content_package(ContentPackage content_package) {
      this.content_package = content_package;
      return this;
    }

    /**
     * owner=
     */
    public Builder feed_package(FeedPackage feed_package) {
      this.feed_package = feed_package;
      return this;
    }

    /**
     * owner=zhaoqi
     */
    public Builder resource_package(ResourcePackage resource_package) {
      this.resource_package = resource_package;
      return this;
    }

    /**
     * owner=
     */
    public Builder open_type_package(OpenTypePackage open_type_package) {
      this.open_type_package = open_type_package;
      return this;
    }

    /**
     * owner=
     */
    public Builder app_status_package(AppStatusPackage app_status_package) {
      this.app_status_package = app_status_package;
      return this;
    }

    @Override
    public ExtraPackage build() {
      return new ExtraPackage(this);
    }
  }
}
