// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_extra_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class FeedPackage extends Message {

  public static final String DEFAULT_IDENTITY = "";
  public static final String DEFAULT_NAME = "";
  public static final String DEFAULT_TEMPLATE = "";
  public static final String DEFAULT_DETAIL = "";

  @ProtoField(tag = 1, type = STRING)
  public final String identity;

  @ProtoField(tag = 2, type = STRING)
  public final String name;

  @ProtoField(tag = 3, type = STRING)
  public final String template;

  @ProtoField(tag = 4, type = STRING)
  public final String detail;

  private FeedPackage(Builder builder) {
    super(builder);
    this.identity = builder.identity;
    this.name = builder.name;
    this.template = builder.template;
    this.detail = builder.detail;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FeedPackage)) return false;
    FeedPackage o = (FeedPackage) other;
    return equals(identity, o.identity)
        && equals(name, o.name)
        && equals(template, o.template)
        && equals(detail, o.detail);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = identity != null ? identity.hashCode() : 0;
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (template != null ? template.hashCode() : 0);
      result = result * 37 + (detail != null ? detail.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<FeedPackage> {

    public String identity;
    public String name;
    public String template;
    public String detail;

    public Builder() {
    }

    public Builder(FeedPackage message) {
      super(message);
      if (message == null) return;
      this.identity = message.identity;
      this.name = message.name;
      this.template = message.template;
      this.detail = message.detail;
    }

    public Builder identity(String identity) {
      this.identity = identity;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder template(String template) {
      this.template = template;
      return this;
    }

    public Builder detail(String detail) {
      this.detail = detail;
      return this;
    }

    @Override
    public FeedPackage build() {
      return new FeedPackage(this);
    }
  }
}
