// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;

public final class FlingEvent extends Message {

  public static final FlingDirection DEFAULT_FLING_DIRECTION = FlingDirection.UP;

  /**
   * 打在View身上的Log
   */
  @ProtoField(tag = 1)
  public final ViewLogPackage view_log_package;

  @ProtoField(tag = 2, type = ENUM)
  public final FlingDirection fling_direction;

  /**
   * 各个业务自己的 package
   */
  @ProtoField(tag = 3)
  public final ExtraPackage extra_package;

  private FlingEvent(Builder builder) {
    super(builder);
    this.view_log_package = builder.view_log_package;
    this.fling_direction = builder.fling_direction;
    this.extra_package = builder.extra_package;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FlingEvent)) return false;
    FlingEvent o = (FlingEvent) other;
    return equals(view_log_package, o.view_log_package)
        && equals(fling_direction, o.fling_direction)
        && equals(extra_package, o.extra_package);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = view_log_package != null ? view_log_package.hashCode() : 0;
      result = result * 37 + (fling_direction != null ? fling_direction.hashCode() : 0);
      result = result * 37 + (extra_package != null ? extra_package.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<FlingEvent> {

    public ViewLogPackage view_log_package;
    public FlingDirection fling_direction;
    public ExtraPackage extra_package;

    public Builder() {
    }

    public Builder(FlingEvent message) {
      super(message);
      if (message == null) return;
      this.view_log_package = message.view_log_package;
      this.fling_direction = message.fling_direction;
      this.extra_package = message.extra_package;
    }

    /**
     * 打在View身上的Log
     */
    public Builder view_log_package(ViewLogPackage view_log_package) {
      this.view_log_package = view_log_package;
      return this;
    }

    public Builder fling_direction(FlingDirection fling_direction) {
      this.fling_direction = fling_direction;
      return this;
    }

    /**
     * 各个业务自己的 package
     */
    public Builder extra_package(ExtraPackage extra_package) {
      this.extra_package = extra_package;
      return this;
    }

    @Override
    public FlingEvent build() {
      return new FlingEvent(this);
    }
  }

  public enum FlingDirection
      implements ProtoEnum {
    UP(0),
    /**
     * 向上
     */
    DOWN(1),
    /**
     * 向下
     */
    LEFT(2),
    /**
     * 向左
     */
    RIGHT(3);

    private final int value;

    private FlingDirection(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
