// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

/**
 * IAS 独有的 Query 信息，owner by lidahai
 */
public final class IASQueryInfoPackage extends Message {

  /**
   * IAS 请求的分桶信息
   */
  @ProtoField(tag = 1)
  public final IASBucketPackage ias_bucket_package;

  /**
   * 请求的结果类型；type(MIXED, APPS, VIDEOS, MUSIC, UNI, etc; sub_type: MUSIC.SONGS, UNI.NEWS, etc)
   */
  @ProtoField(tag = 2)
  public final ContentPackage ias_request_content_package;

  private IASQueryInfoPackage(Builder builder) {
    super(builder);
    this.ias_bucket_package = builder.ias_bucket_package;
    this.ias_request_content_package = builder.ias_request_content_package;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof IASQueryInfoPackage)) return false;
    IASQueryInfoPackage o = (IASQueryInfoPackage) other;
    return equals(ias_bucket_package, o.ias_bucket_package)
        && equals(ias_request_content_package, o.ias_request_content_package);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = ias_bucket_package != null ? ias_bucket_package.hashCode() : 0;
      result = result * 37 + (ias_request_content_package != null ? ias_request_content_package.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<IASQueryInfoPackage> {

    public IASBucketPackage ias_bucket_package;
    public ContentPackage ias_request_content_package;

    public Builder() {
    }

    public Builder(IASQueryInfoPackage message) {
      super(message);
      if (message == null) return;
      this.ias_bucket_package = message.ias_bucket_package;
      this.ias_request_content_package = message.ias_request_content_package;
    }

    /**
     * IAS 请求的分桶信息
     */
    public Builder ias_bucket_package(IASBucketPackage ias_bucket_package) {
      this.ias_bucket_package = ias_bucket_package;
      return this;
    }

    /**
     * 请求的结果类型；type(MIXED, APPS, VIDEOS, MUSIC, UNI, etc; sub_type: MUSIC.SONGS, UNI.NEWS, etc)
     */
    public Builder ias_request_content_package(ContentPackage ias_request_content_package) {
      this.ias_request_content_package = ias_request_content_package;
      return this;
    }

    @Override
    public IASQueryInfoPackage build() {
      return new IASQueryInfoPackage(this);
    }
  }

  /**
   * IAS 分桶信息
   */
  public static final class IASBucketPackage extends Message {

    public static final Integer DEFAULT_USER_BUCKET_ID = 0;
    public static final Integer DEFAULT_SESSION_BUICKET_ID = 0;

    @ProtoField(tag = 1, type = INT32)
    public final Integer user_bucket_id;

    @ProtoField(tag = 2, type = INT32)
    public final Integer session_buicket_id;

    private IASBucketPackage(Builder builder) {
      super(builder);
      this.user_bucket_id = builder.user_bucket_id;
      this.session_buicket_id = builder.session_buicket_id;
    }

    @Override
    public boolean equals(Object other) {
      if (other == this) return true;
      if (!(other instanceof IASBucketPackage)) return false;
      IASBucketPackage o = (IASBucketPackage) other;
      return equals(user_bucket_id, o.user_bucket_id)
          && equals(session_buicket_id, o.session_buicket_id);
    }

    @Override
    public int hashCode() {
      int result = hashCode;
      if (result == 0) {
        result = user_bucket_id != null ? user_bucket_id.hashCode() : 0;
        result = result * 37 + (session_buicket_id != null ? session_buicket_id.hashCode() : 0);
        hashCode = result;
      }
      return result;
    }

    public static final class Builder extends Message.Builder<IASBucketPackage> {

      public Integer user_bucket_id;
      public Integer session_buicket_id;

      public Builder() {
      }

      public Builder(IASBucketPackage message) {
        super(message);
        if (message == null) return;
        this.user_bucket_id = message.user_bucket_id;
        this.session_buicket_id = message.session_buicket_id;
      }

      public Builder user_bucket_id(Integer user_bucket_id) {
        this.user_bucket_id = user_bucket_id;
        return this;
      }

      public Builder session_buicket_id(Integer session_buicket_id) {
        this.session_buicket_id = session_buicket_id;
        return this;
      }

      @Override
      public IASBucketPackage build() {
        return new IASBucketPackage(this);
      }
    }
  }
}
