// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.FLOAT;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * IAS 独有的 search result 信息，owner by lidahai
 */
public final class IASSearchResultPackage extends Message {

  public static final List<QueryUnderstandingScore> DEFAULT_QUERY_UNDERSTANDING_RESULT = Collections.emptyList();
  public static final List<SectionResultPackage> DEFAULT_SECTION_RESULT = Collections.emptyList();
  public static final String DEFAULT_ITEM_ID = "";

  @ProtoField(tag = 1, label = REPEATED)
  public final List<QueryUnderstandingScore> query_understanding_result;

  @ProtoField(tag = 2, label = REPEATED)
  public final List<SectionResultPackage> section_result;

  /**
   * item id
   */
  @ProtoField(tag = 3, type = STRING)
  public final String item_id;

  private IASSearchResultPackage(Builder builder) {
    super(builder);
    this.query_understanding_result = immutableCopyOf(builder.query_understanding_result);
    this.section_result = immutableCopyOf(builder.section_result);
    this.item_id = builder.item_id;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof IASSearchResultPackage)) return false;
    IASSearchResultPackage o = (IASSearchResultPackage) other;
    return equals(query_understanding_result, o.query_understanding_result)
        && equals(section_result, o.section_result)
        && equals(item_id, o.item_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = query_understanding_result != null ? query_understanding_result.hashCode() : 1;
      result = result * 37 + (section_result != null ? section_result.hashCode() : 1);
      result = result * 37 + (item_id != null ? item_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<IASSearchResultPackage> {

    public List<QueryUnderstandingScore> query_understanding_result;
    public List<SectionResultPackage> section_result;
    public String item_id;

    public Builder() {
    }

    public Builder(IASSearchResultPackage message) {
      super(message);
      if (message == null) return;
      this.query_understanding_result = copyOf(message.query_understanding_result);
      this.section_result = copyOf(message.section_result);
      this.item_id = message.item_id;
    }

    public Builder query_understanding_result(List<QueryUnderstandingScore> query_understanding_result) {
      this.query_understanding_result = checkForNulls(query_understanding_result);
      return this;
    }

    public Builder section_result(List<SectionResultPackage> section_result) {
      this.section_result = checkForNulls(section_result);
      return this;
    }

    /**
     * item id
     */
    public Builder item_id(String item_id) {
      this.item_id = item_id;
      return this;
    }

    @Override
    public IASSearchResultPackage build() {
      return new IASSearchResultPackage(this);
    }
  }

  /**
   * IAS QueryUnderstanding结果
   */
  public static final class QueryUnderstandingScore extends Message {

    public static final String DEFAULT_CONTENT_VERTICAL_TYPE = "";
    public static final Float DEFAULT_SCORE = 0F;

    @ProtoField(tag = 1, type = STRING, label = REQUIRED)
    public final String content_vertical_type;

    /**
     * query 打分
     */
    @ProtoField(tag = 2, type = FLOAT, label = REQUIRED)
    public final Float score;

    private QueryUnderstandingScore(Builder builder) {
      super(builder);
      this.content_vertical_type = builder.content_vertical_type;
      this.score = builder.score;
    }

    @Override
    public boolean equals(Object other) {
      if (other == this) return true;
      if (!(other instanceof QueryUnderstandingScore)) return false;
      QueryUnderstandingScore o = (QueryUnderstandingScore) other;
      return equals(content_vertical_type, o.content_vertical_type)
          && equals(score, o.score);
    }

    @Override
    public int hashCode() {
      int result = hashCode;
      if (result == 0) {
        result = content_vertical_type != null ? content_vertical_type.hashCode() : 0;
        result = result * 37 + (score != null ? score.hashCode() : 0);
        hashCode = result;
      }
      return result;
    }

    public static final class Builder extends Message.Builder<QueryUnderstandingScore> {

      public String content_vertical_type;
      public Float score;

      public Builder() {
      }

      public Builder(QueryUnderstandingScore message) {
        super(message);
        if (message == null) return;
        this.content_vertical_type = message.content_vertical_type;
        this.score = message.score;
      }

      public Builder content_vertical_type(String content_vertical_type) {
        this.content_vertical_type = content_vertical_type;
        return this;
      }

      /**
       * query 打分
       */
      public Builder score(Float score) {
        this.score = score;
        return this;
      }

      @Override
      public QueryUnderstandingScore build() {
        checkRequiredFields();
        return new QueryUnderstandingScore(this);
      }
    }
  }

  /**
   * section 结果; 当前 IAS v2 独有
   */
  public static final class SectionResultPackage extends Message {

    public static final String DEFAULT_SECTION_TYPE = "";
    public static final String DEFAULT_TITLE = "";
    public static final Integer DEFAULT_ITEM_NUM = 0;

    /**
     * APP, WALLPAPERS, VIDEOS, MIXED, etc.
     */
    @ProtoField(tag = 1, type = STRING)
    public final String section_type;

    /**
     * section 标题
     */
    @ProtoField(tag = 2, type = STRING)
    public final String title;

    /**
     * item 个数
     */
    @ProtoField(tag = 3, type = INT32)
    public final Integer item_num;

    private SectionResultPackage(Builder builder) {
      super(builder);
      this.section_type = builder.section_type;
      this.title = builder.title;
      this.item_num = builder.item_num;
    }

    @Override
    public boolean equals(Object other) {
      if (other == this) return true;
      if (!(other instanceof SectionResultPackage)) return false;
      SectionResultPackage o = (SectionResultPackage) other;
      return equals(section_type, o.section_type)
          && equals(title, o.title)
          && equals(item_num, o.item_num);
    }

    @Override
    public int hashCode() {
      int result = hashCode;
      if (result == 0) {
        result = section_type != null ? section_type.hashCode() : 0;
        result = result * 37 + (title != null ? title.hashCode() : 0);
        result = result * 37 + (item_num != null ? item_num.hashCode() : 0);
        hashCode = result;
      }
      return result;
    }

    public static final class Builder extends Message.Builder<SectionResultPackage> {

      public String section_type;
      public String title;
      public Integer item_num;

      public Builder() {
      }

      public Builder(SectionResultPackage message) {
        super(message);
        if (message == null) return;
        this.section_type = message.section_type;
        this.title = message.title;
        this.item_num = message.item_num;
      }

      /**
       * APP, WALLPAPERS, VIDEOS, MIXED, etc.
       */
      public Builder section_type(String section_type) {
        this.section_type = section_type;
        return this;
      }

      /**
       * section 标题
       */
      public Builder title(String title) {
        this.title = title;
        return this;
      }

      /**
       * item 个数
       */
      public Builder item_num(Integer item_num) {
        this.item_num = item_num;
        return this;
      }

      @Override
      public SectionResultPackage build() {
        return new SectionResultPackage(this);
      }
    }
  }
}
