// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_common_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ID信息
 */
public final class IdPackage extends Message {

  public static final String DEFAULT_IDENTITY = "";
  public static final String DEFAULT_UDID = "";
  public static final String DEFAULT_PCID = "";

  /**
   * major id，如果是移动设备id=udid,如果是pc设备id=pcid
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String identity;

  /**
   * 移动设备的 id
   */
  @ProtoField(tag = 2, type = STRING)
  public final String udid;

  /**
   * PC 的 id
   */
  @ProtoField(tag = 3, type = STRING)
  public final String pcid;

  private IdPackage(Builder builder) {
    super(builder);
    this.identity = builder.identity;
    this.udid = builder.udid;
    this.pcid = builder.pcid;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof IdPackage)) return false;
    IdPackage o = (IdPackage) other;
    return equals(identity, o.identity)
        && equals(udid, o.udid)
        && equals(pcid, o.pcid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = identity != null ? identity.hashCode() : 0;
      result = result * 37 + (udid != null ? udid.hashCode() : 0);
      result = result * 37 + (pcid != null ? pcid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<IdPackage> {

    public String identity;
    public String udid;
    public String pcid;

    public Builder() {
    }

    public Builder(IdPackage message) {
      super(message);
      if (message == null) return;
      this.identity = message.identity;
      this.udid = message.udid;
      this.pcid = message.pcid;
    }

    /**
     * major id，如果是移动设备id=udid,如果是pc设备id=pcid
     */
    public Builder identity(String identity) {
      this.identity = identity;
      return this;
    }

    /**
     * 移动设备的 id
     */
    public Builder udid(String udid) {
      this.udid = udid;
      return this;
    }

    /**
     * PC 的 id
     */
    public Builder pcid(String pcid) {
      this.pcid = pcid;
      return this;
    }

    @Override
    public IdPackage build() {
      checkRequiredFields();
      return new IdPackage(this);
    }
  }
}
