// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_common_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * P4启动来源信息
 */
public final class LaunchSourcePackage extends Message {

  public static final Source DEFAULT_SOURCE = Source.UNKNOWN;
  public static final String DEFAULT_KEYWORD = "";

  /**
   * 启动来源 (现有welcome, shortcut, widget, market)
   */
  @ProtoField(tag = 1, type = ENUM)
  public final Source source;

  /**
   * 启动的关键词，如 通知栏 中，可以带有通知栏的内容作为 keyword
   */
  @ProtoField(tag = 2, type = STRING)
  public final String keyword;

  private LaunchSourcePackage(Builder builder) {
    super(builder);
    this.source = builder.source;
    this.keyword = builder.keyword;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LaunchSourcePackage)) return false;
    LaunchSourcePackage o = (LaunchSourcePackage) other;
    return equals(source, o.source)
        && equals(keyword, o.keyword);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = source != null ? source.hashCode() : 0;
      result = result * 37 + (keyword != null ? keyword.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LaunchSourcePackage> {

    public Source source;
    public String keyword;

    public Builder() {
    }

    public Builder(LaunchSourcePackage message) {
      super(message);
      if (message == null) return;
      this.source = message.source;
      this.keyword = message.keyword;
    }

    /**
     * 启动来源 (现有welcome, shortcut, widget, market)
     */
    public Builder source(Source source) {
      this.source = source;
      return this;
    }

    /**
     * 启动的关键词，如 通知栏 中，可以带有通知栏的内容作为 keyword
     */
    public Builder keyword(String keyword) {
      this.keyword = keyword;
      return this;
    }

    @Override
    public LaunchSourcePackage build() {
      return new LaunchSourcePackage(this);
    }
  }

  public enum Source
      implements ProtoEnum {
    UNKNOWN(0),
    /**
     * 来源未知
     */
    WELCOME(1),
    /**
     * 正常进入欢迎页
     */
    SHORTCUT(2),
    /**
     * 快捷方式
     */
    WIDGET(3),
    /**
     * 桌面控件
     */
    MARKET(4),
    /**
     * 监控市场跳转
     */
    START(5),
    NOTIFICATION_DOWNLOAD(6),
    NOTIFICATION_SELF_UPGRADE(7),
    NOTIFICATION_XIBAIBAI(8),
    NOTIFICATION_CLEAN(9),
    NOTIFICATION_PUSH(10),
    NOTIFICATION_PUSH_APP(11),
    NOTIFICATION_APP(12),
    NOTIFICATION_VIDEO(13),
    NOTIFICATION_EBOOK(14),
    NOTIFICATION_WALLPAPER(15),
    NOTIFICATION_FREE_TRAFFIC(16),
    NOTIFICATION_SYNC(17);

    private final int value;

    private Source(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
