// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 订单信息
 */
public final class OrderPackage extends Message {

  public static final Integer DEFAULT_ORDER_ID = 0;
  public static final Integer DEFAULT_LINK_ORDER_ID = 0;
  public static final Integer DEFAULT_APP_KEY_ID = 0;
  public static final String DEFAULT_DEFAULT_CHARGE_TYPE = "";
  public static final Integer DEFAULT_DEFAULT_MONEY = 0;
  public static final Integer DEFAULT_ORDER_MONEY = 0;
  public static final String DEFAULT_CHARGE_TYPE = "";
  public static final Integer DEFAULT_MONEY = 0;
  public static final String DEFAULT_TRADE_STATUS = "";

  /**
   * 订单 ID
   */
  @ProtoField(tag = 1, type = INT32)
  public final Integer order_id;

  /**
   * 关联 ID
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer link_order_id;

  /**
   * 联运游戏 ID
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer app_key_id;

  /**
   * 默认支付方式
   */
  @ProtoField(tag = 4, type = STRING)
  public final String default_charge_type;

  /**
   * 默认支付金额（单位：分）
   */
  @ProtoField(tag = 5, type = INT32)
  public final Integer default_money;

  /**
   * 订单金额（单位：分）
   */
  @ProtoField(tag = 6, type = INT32)
  public final Integer order_money;

  /**
   * 支付方式
   */
  @ProtoField(tag = 7, type = STRING)
  public final String charge_type;

  /**
   * 支付金额（单位：分）
   */
  @ProtoField(tag = 8, type = INT32)
  public final Integer money;

  /**
   * 订单结果
   */
  @ProtoField(tag = 9, type = STRING)
  public final String trade_status;

  private OrderPackage(Builder builder) {
    super(builder);
    this.order_id = builder.order_id;
    this.link_order_id = builder.link_order_id;
    this.app_key_id = builder.app_key_id;
    this.default_charge_type = builder.default_charge_type;
    this.default_money = builder.default_money;
    this.order_money = builder.order_money;
    this.charge_type = builder.charge_type;
    this.money = builder.money;
    this.trade_status = builder.trade_status;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof OrderPackage)) return false;
    OrderPackage o = (OrderPackage) other;
    return equals(order_id, o.order_id)
        && equals(link_order_id, o.link_order_id)
        && equals(app_key_id, o.app_key_id)
        && equals(default_charge_type, o.default_charge_type)
        && equals(default_money, o.default_money)
        && equals(order_money, o.order_money)
        && equals(charge_type, o.charge_type)
        && equals(money, o.money)
        && equals(trade_status, o.trade_status);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = order_id != null ? order_id.hashCode() : 0;
      result = result * 37 + (link_order_id != null ? link_order_id.hashCode() : 0);
      result = result * 37 + (app_key_id != null ? app_key_id.hashCode() : 0);
      result = result * 37 + (default_charge_type != null ? default_charge_type.hashCode() : 0);
      result = result * 37 + (default_money != null ? default_money.hashCode() : 0);
      result = result * 37 + (order_money != null ? order_money.hashCode() : 0);
      result = result * 37 + (charge_type != null ? charge_type.hashCode() : 0);
      result = result * 37 + (money != null ? money.hashCode() : 0);
      result = result * 37 + (trade_status != null ? trade_status.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<OrderPackage> {

    public Integer order_id;
    public Integer link_order_id;
    public Integer app_key_id;
    public String default_charge_type;
    public Integer default_money;
    public Integer order_money;
    public String charge_type;
    public Integer money;
    public String trade_status;

    public Builder() {
    }

    public Builder(OrderPackage message) {
      super(message);
      if (message == null) return;
      this.order_id = message.order_id;
      this.link_order_id = message.link_order_id;
      this.app_key_id = message.app_key_id;
      this.default_charge_type = message.default_charge_type;
      this.default_money = message.default_money;
      this.order_money = message.order_money;
      this.charge_type = message.charge_type;
      this.money = message.money;
      this.trade_status = message.trade_status;
    }

    /**
     * 订单 ID
     */
    public Builder order_id(Integer order_id) {
      this.order_id = order_id;
      return this;
    }

    /**
     * 关联 ID
     */
    public Builder link_order_id(Integer link_order_id) {
      this.link_order_id = link_order_id;
      return this;
    }

    /**
     * 联运游戏 ID
     */
    public Builder app_key_id(Integer app_key_id) {
      this.app_key_id = app_key_id;
      return this;
    }

    /**
     * 默认支付方式
     */
    public Builder default_charge_type(String default_charge_type) {
      this.default_charge_type = default_charge_type;
      return this;
    }

    /**
     * 默认支付金额（单位：分）
     */
    public Builder default_money(Integer default_money) {
      this.default_money = default_money;
      return this;
    }

    /**
     * 订单金额（单位：分）
     */
    public Builder order_money(Integer order_money) {
      this.order_money = order_money;
      return this;
    }

    /**
     * 支付方式
     */
    public Builder charge_type(String charge_type) {
      this.charge_type = charge_type;
      return this;
    }

    /**
     * 支付金额（单位：分）
     */
    public Builder money(Integer money) {
      this.money = money;
      return this;
    }

    /**
     * 订单结果
     */
    public Builder trade_status(String trade_status) {
      this.trade_status = trade_status;
      return this;
    }

    @Override
    public OrderPackage build() {
      return new OrderPackage(this);
    }
  }
}
