// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_extra_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 资源信息包
 */
public final class ResourcePackage extends Message {

  public static final String DEFAULT_IDENTITY = "";
  public static final Type DEFAULT_TYPE = Type.WDJ_HOSTED;
  public static final String DEFAULT_PROVIDER_NAME = "";
  public static final String DEFAULT_APP_URI = "";
  public static final Boolean DEFAULT_CAN_DOWNLOAD = false;

  /**
   * 资源id
   */
  @ProtoField(tag = 1, type = STRING)
  public final String identity;

  /**
   * 资源类型
   */
  @ProtoField(tag = 2, type = ENUM)
  public final Type type;

  /**
   * 提供方名称
   */
  @ProtoField(tag = 3, type = STRING)
  public final String provider_name;

  /**
   * 应用的播放地址标识。相对于我们自己host的内容，这里是去对方的应用去播放的对方的地址。
   */
  @ProtoField(tag = 4, type = STRING)
  public final String app_uri;

  /**
   * 是否可以下载
   */
  @ProtoField(tag = 5, type = BOOL)
  public final Boolean can_download;

  private ResourcePackage(Builder builder) {
    super(builder);
    this.identity = builder.identity;
    this.type = builder.type;
    this.provider_name = builder.provider_name;
    this.app_uri = builder.app_uri;
    this.can_download = builder.can_download;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ResourcePackage)) return false;
    ResourcePackage o = (ResourcePackage) other;
    return equals(identity, o.identity)
        && equals(type, o.type)
        && equals(provider_name, o.provider_name)
        && equals(app_uri, o.app_uri)
        && equals(can_download, o.can_download);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = identity != null ? identity.hashCode() : 0;
      result = result * 37 + (type != null ? type.hashCode() : 0);
      result = result * 37 + (provider_name != null ? provider_name.hashCode() : 0);
      result = result * 37 + (app_uri != null ? app_uri.hashCode() : 0);
      result = result * 37 + (can_download != null ? can_download.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ResourcePackage> {

    public String identity;
    public Type type;
    public String provider_name;
    public String app_uri;
    public Boolean can_download;

    public Builder() {
    }

    public Builder(ResourcePackage message) {
      super(message);
      if (message == null) return;
      this.identity = message.identity;
      this.type = message.type;
      this.provider_name = message.provider_name;
      this.app_uri = message.app_uri;
      this.can_download = message.can_download;
    }

    /**
     * 资源id
     */
    public Builder identity(String identity) {
      this.identity = identity;
      return this;
    }

    /**
     * 资源类型
     */
    public Builder type(Type type) {
      this.type = type;
      return this;
    }

    /**
     * 提供方名称
     */
    public Builder provider_name(String provider_name) {
      this.provider_name = provider_name;
      return this;
    }

    /**
     * 应用的播放地址标识。相对于我们自己host的内容，这里是去对方的应用去播放的对方的地址。
     */
    public Builder app_uri(String app_uri) {
      this.app_uri = app_uri;
      return this;
    }

    /**
     * 是否可以下载
     */
    public Builder can_download(Boolean can_download) {
      this.can_download = can_download;
      return this;
    }

    @Override
    public ResourcePackage build() {
      return new ResourcePackage(this);
    }
  }

  public enum Type
      implements ProtoEnum {
    WDJ_HOSTED(0),
    /**
     * wdj host 的资源
     */
    PARTNER_COMMON(1),
    /**
     * 合作方的通用格式资源
     */
    PARTNER_PRIVATE(2);

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
