// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * 搜索结果信息
 */
public final class SearchResultPackage extends Message {

  public static final Boolean DEFAULT_ADJUSTED = false;
  public static final List<ContentPackage> DEFAULT_SEARCH_RESULT_PACKAGE = Collections.emptyList();

  /**
   * 是否有人工干预
   */
  @ProtoField(tag = 1, type = BOOL)
  public final Boolean adjusted;

  /**
   * item result
   */
  @ProtoField(tag = 2, label = REPEATED)
  public final List<ContentPackage> search_result_package;

  private SearchResultPackage(Builder builder) {
    super(builder);
    this.adjusted = builder.adjusted;
    this.search_result_package = immutableCopyOf(builder.search_result_package);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SearchResultPackage)) return false;
    SearchResultPackage o = (SearchResultPackage) other;
    return equals(adjusted, o.adjusted)
        && equals(search_result_package, o.search_result_package);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = adjusted != null ? adjusted.hashCode() : 0;
      result = result * 37 + (search_result_package != null ? search_result_package.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SearchResultPackage> {

    public Boolean adjusted;
    public List<ContentPackage> search_result_package;

    public Builder() {
    }

    public Builder(SearchResultPackage message) {
      super(message);
      if (message == null) return;
      this.adjusted = message.adjusted;
      this.search_result_package = copyOf(message.search_result_package);
    }

    /**
     * 是否有人工干预
     */
    public Builder adjusted(Boolean adjusted) {
      this.adjusted = adjusted;
      return this;
    }

    /**
     * item result
     */
    public Builder search_result_package(List<ContentPackage> search_result_package) {
      this.search_result_package = checkForNulls(search_result_package);
      return this;
    }

    @Override
    public SearchResultPackage build() {
      return new SearchResultPackage(this);
    }
  }
}
