// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 服务器信息
 */
public final class ServerHostPackage extends Message {

  public static final String DEFAULT_HOST_IP = "";
  public static final String DEFAULT_HOST_NAME = "";

  /**
   * 主机地址，格式xxx.xxx.xxx.xxx，不够3位数不补0
   */
  @ProtoField(tag = 1, type = STRING)
  public final String host_ip;

  /**
   * 主机名字
   */
  @ProtoField(tag = 2, type = STRING)
  public final String host_name;

  private ServerHostPackage(Builder builder) {
    super(builder);
    this.host_ip = builder.host_ip;
    this.host_name = builder.host_name;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ServerHostPackage)) return false;
    ServerHostPackage o = (ServerHostPackage) other;
    return equals(host_ip, o.host_ip)
        && equals(host_name, o.host_name);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = host_ip != null ? host_ip.hashCode() : 0;
      result = result * 37 + (host_name != null ? host_name.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ServerHostPackage> {

    public String host_ip;
    public String host_name;

    public Builder() {
    }

    public Builder(ServerHostPackage message) {
      super(message);
      if (message == null) return;
      this.host_ip = message.host_ip;
      this.host_name = message.host_name;
    }

    /**
     * 主机地址，格式xxx.xxx.xxx.xxx，不够3位数不补0
     */
    public Builder host_ip(String host_ip) {
      this.host_ip = host_ip;
      return this;
    }

    /**
     * 主机名字
     */
    public Builder host_name(String host_name) {
      this.host_name = host_name;
      return this;
    }

    @Override
    public ServerHostPackage build() {
      return new ServerHostPackage(this);
    }
  }
}
