// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_event_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;

/**
 * 展示
 */
public final class ShowEvent extends Message {

  public static final Type DEFAULT_TYPE = Type.PAGE;

  /**
   * 展示 log 类型
   */
  @ProtoField(tag = 1, type = ENUM)
  public final Type type;

  /**
   * 打在View身上的Log
   */
  @ProtoField(tag = 2)
  public final ViewLogPackage view;

  /**
   * 上一个页面
   */
  @ProtoField(tag = 3)
  public final ViewLogPackage from_page;

  /**
   * 上一次点击
   */
  @ProtoField(tag = 4)
  public final ViewLogPackage refer_click;

  /**
   * 上一个页面的最后一次点击
   */
  @ProtoField(tag = 5)
  public final ViewLogPackage from_click;

  private ShowEvent(Builder builder) {
    super(builder);
    this.type = builder.type;
    this.view = builder.view;
    this.from_page = builder.from_page;
    this.refer_click = builder.refer_click;
    this.from_click = builder.from_click;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ShowEvent)) return false;
    ShowEvent o = (ShowEvent) other;
    return equals(type, o.type)
        && equals(view, o.view)
        && equals(from_page, o.from_page)
        && equals(refer_click, o.refer_click)
        && equals(from_click, o.from_click);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = type != null ? type.hashCode() : 0;
      result = result * 37 + (view != null ? view.hashCode() : 0);
      result = result * 37 + (from_page != null ? from_page.hashCode() : 0);
      result = result * 37 + (refer_click != null ? refer_click.hashCode() : 0);
      result = result * 37 + (from_click != null ? from_click.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ShowEvent> {

    public Type type;
    public ViewLogPackage view;
    public ViewLogPackage from_page;
    public ViewLogPackage refer_click;
    public ViewLogPackage from_click;

    public Builder() {
    }

    public Builder(ShowEvent message) {
      super(message);
      if (message == null) return;
      this.type = message.type;
      this.view = message.view;
      this.from_page = message.from_page;
      this.refer_click = message.refer_click;
      this.from_click = message.from_click;
    }

    /**
     * 展示 log 类型
     */
    public Builder type(Type type) {
      this.type = type;
      return this;
    }

    /**
     * 打在View身上的Log
     */
    public Builder view(ViewLogPackage view) {
      this.view = view;
      return this;
    }

    /**
     * 上一个页面
     */
    public Builder from_page(ViewLogPackage from_page) {
      this.from_page = from_page;
      return this;
    }

    /**
     * 上一次点击
     */
    public Builder refer_click(ViewLogPackage refer_click) {
      this.refer_click = refer_click;
      return this;
    }

    /**
     * 上一个页面的最后一次点击
     */
    public Builder from_click(ViewLogPackage from_click) {
      this.from_click = from_click;
      return this;
    }

    @Override
    public ShowEvent build() {
      return new ShowEvent(this);
    }
  }

  public enum Type
      implements ProtoEnum {
    PAGE(0),
    /**
     * 页面展示
     */
    CARD(1);

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
