// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 首页卡片信息包
 */
public final class StartpageCardPackage extends Message {

  public static final String DEFAULT_STARTPAGE_CARD_FEED_NAME = "";
  public static final String DEFAULT_STARTPAGE_CARD_TEMPLATE = "";
  public static final String DEFAULT_STARTPAGE_CARD_ID = "";
  public static final String DEFAULT_STARTPAGE_SUB_CARD_LIST = "";

  /**
   * feed name
   */
  @ProtoField(tag = 1, type = STRING)
  public final String startpage_card_feed_name;

  /**
   * 模版
   */
  @ProtoField(tag = 2, type = STRING)
  public final String startpage_card_template;

  /**
   * 首页标识的卡片id
   */
  @ProtoField(tag = 3, type = STRING)
  public final String startpage_card_id;

  /**
   * 下发了哪些条目
   */
  @ProtoField(tag = 4, type = STRING)
  public final String startpage_sub_card_list;

  private StartpageCardPackage(Builder builder) {
    super(builder);
    this.startpage_card_feed_name = builder.startpage_card_feed_name;
    this.startpage_card_template = builder.startpage_card_template;
    this.startpage_card_id = builder.startpage_card_id;
    this.startpage_sub_card_list = builder.startpage_sub_card_list;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof StartpageCardPackage)) return false;
    StartpageCardPackage o = (StartpageCardPackage) other;
    return equals(startpage_card_feed_name, o.startpage_card_feed_name)
        && equals(startpage_card_template, o.startpage_card_template)
        && equals(startpage_card_id, o.startpage_card_id)
        && equals(startpage_sub_card_list, o.startpage_sub_card_list);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = startpage_card_feed_name != null ? startpage_card_feed_name.hashCode() : 0;
      result = result * 37 + (startpage_card_template != null ? startpage_card_template.hashCode() : 0);
      result = result * 37 + (startpage_card_id != null ? startpage_card_id.hashCode() : 0);
      result = result * 37 + (startpage_sub_card_list != null ? startpage_sub_card_list.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<StartpageCardPackage> {

    public String startpage_card_feed_name;
    public String startpage_card_template;
    public String startpage_card_id;
    public String startpage_sub_card_list;

    public Builder() {
    }

    public Builder(StartpageCardPackage message) {
      super(message);
      if (message == null) return;
      this.startpage_card_feed_name = message.startpage_card_feed_name;
      this.startpage_card_template = message.startpage_card_template;
      this.startpage_card_id = message.startpage_card_id;
      this.startpage_sub_card_list = message.startpage_sub_card_list;
    }

    /**
     * feed name
     */
    public Builder startpage_card_feed_name(String startpage_card_feed_name) {
      this.startpage_card_feed_name = startpage_card_feed_name;
      return this;
    }

    /**
     * 模版
     */
    public Builder startpage_card_template(String startpage_card_template) {
      this.startpage_card_template = startpage_card_template;
      return this;
    }

    /**
     * 首页标识的卡片id
     */
    public Builder startpage_card_id(String startpage_card_id) {
      this.startpage_card_id = startpage_card_id;
      return this;
    }

    /**
     * 下发了哪些条目
     */
    public Builder startpage_sub_card_list(String startpage_sub_card_list) {
      this.startpage_sub_card_list = startpage_sub_card_list;
      return this;
    }

    @Override
    public StartpageCardPackage build() {
      return new StartpageCardPackage(this);
    }
  }
}
