// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class SubscribeSubsetPackage extends Message {

  public static final String DEFAULT_ITEMLISTTYPE = "";
  public static final String DEFAULT_SUBSET_TITLE = "";
  public static final String DEFAULT_SUBSET_TYPE = "";
  public static final String DEFAULT_SUBSET_ID = "";
  public static final String DEFAULT_SUBSET_CREATETIME = "";
  public static final String DEFAULT_SUBSET_UPDATETIME = "";

  @ProtoField(tag = 1, type = STRING)
  public final String itemlistType;

  @ProtoField(tag = 2, type = STRING)
  public final String subset_title;

  @ProtoField(tag = 3, type = STRING)
  public final String subset_type;

  @ProtoField(tag = 4, type = STRING)
  public final String subset_id;

  @ProtoField(tag = 5, type = STRING)
  public final String subset_createTime;

  @ProtoField(tag = 6, type = STRING)
  public final String subset_updateTime;

  @ProtoField(tag = 7)
  public final SubscribePublisherPackage publisher;

  private SubscribeSubsetPackage(Builder builder) {
    super(builder);
    this.itemlistType = builder.itemlistType;
    this.subset_title = builder.subset_title;
    this.subset_type = builder.subset_type;
    this.subset_id = builder.subset_id;
    this.subset_createTime = builder.subset_createTime;
    this.subset_updateTime = builder.subset_updateTime;
    this.publisher = builder.publisher;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SubscribeSubsetPackage)) return false;
    SubscribeSubsetPackage o = (SubscribeSubsetPackage) other;
    return equals(itemlistType, o.itemlistType)
        && equals(subset_title, o.subset_title)
        && equals(subset_type, o.subset_type)
        && equals(subset_id, o.subset_id)
        && equals(subset_createTime, o.subset_createTime)
        && equals(subset_updateTime, o.subset_updateTime)
        && equals(publisher, o.publisher);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = itemlistType != null ? itemlistType.hashCode() : 0;
      result = result * 37 + (subset_title != null ? subset_title.hashCode() : 0);
      result = result * 37 + (subset_type != null ? subset_type.hashCode() : 0);
      result = result * 37 + (subset_id != null ? subset_id.hashCode() : 0);
      result = result * 37 + (subset_createTime != null ? subset_createTime.hashCode() : 0);
      result = result * 37 + (subset_updateTime != null ? subset_updateTime.hashCode() : 0);
      result = result * 37 + (publisher != null ? publisher.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SubscribeSubsetPackage> {

    public String itemlistType;
    public String subset_title;
    public String subset_type;
    public String subset_id;
    public String subset_createTime;
    public String subset_updateTime;
    public SubscribePublisherPackage publisher;

    public Builder() {
    }

    public Builder(SubscribeSubsetPackage message) {
      super(message);
      if (message == null) return;
      this.itemlistType = message.itemlistType;
      this.subset_title = message.subset_title;
      this.subset_type = message.subset_type;
      this.subset_id = message.subset_id;
      this.subset_createTime = message.subset_createTime;
      this.subset_updateTime = message.subset_updateTime;
      this.publisher = message.publisher;
    }

    public Builder itemlistType(String itemlistType) {
      this.itemlistType = itemlistType;
      return this;
    }

    public Builder subset_title(String subset_title) {
      this.subset_title = subset_title;
      return this;
    }

    public Builder subset_type(String subset_type) {
      this.subset_type = subset_type;
      return this;
    }

    public Builder subset_id(String subset_id) {
      this.subset_id = subset_id;
      return this;
    }

    public Builder subset_createTime(String subset_createTime) {
      this.subset_createTime = subset_createTime;
      return this;
    }

    public Builder subset_updateTime(String subset_updateTime) {
      this.subset_updateTime = subset_updateTime;
      return this;
    }

    public Builder publisher(SubscribePublisherPackage publisher) {
      this.publisher = publisher;
      return this;
    }

    @Override
    public SubscribeSubsetPackage build() {
      return new SubscribeSubsetPackage(this);
    }
  }
}
