// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.STRING;

public final class SubscribePublisherPackage extends Message {

  public static final String DEFAULT_PUBLISHER_TYPE = "";
  public static final String DEFAULT_PUBLISHER_ID = "";
  public static final String DEFAULT_PUBLISHER_NICK = "";
  public static final String DEFAULT_PUBLISHER_SUBSCRIBEDCOUNT = "";
  public static final Boolean DEFAULT_PUBLISHER_SUBSCRIBED = false;
  public static final Boolean DEFAULT_PUBLISHER_DEFAULTSELECTED = false;

  @ProtoField(tag = 1, type = STRING)
  public final String publisher_type;

  @ProtoField(tag = 2, type = STRING)
  public final String publisher_id;

  @ProtoField(tag = 3, type = STRING)
  public final String publisher_nick;

  @ProtoField(tag = 4, type = STRING)
  public final String publisher_subscribedCount;

  @ProtoField(tag = 5, type = BOOL)
  public final Boolean publisher_subscribed;

  @ProtoField(tag = 6, type = BOOL)
  public final Boolean publisher_defaultSelected;

  private SubscribePublisherPackage(Builder builder) {
    super(builder);
    this.publisher_type = builder.publisher_type;
    this.publisher_id = builder.publisher_id;
    this.publisher_nick = builder.publisher_nick;
    this.publisher_subscribedCount = builder.publisher_subscribedCount;
    this.publisher_subscribed = builder.publisher_subscribed;
    this.publisher_defaultSelected = builder.publisher_defaultSelected;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SubscribePublisherPackage)) return false;
    SubscribePublisherPackage o = (SubscribePublisherPackage) other;
    return equals(publisher_type, o.publisher_type)
        && equals(publisher_id, o.publisher_id)
        && equals(publisher_nick, o.publisher_nick)
        && equals(publisher_subscribedCount, o.publisher_subscribedCount)
        && equals(publisher_subscribed, o.publisher_subscribed)
        && equals(publisher_defaultSelected, o.publisher_defaultSelected);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = publisher_type != null ? publisher_type.hashCode() : 0;
      result = result * 37 + (publisher_id != null ? publisher_id.hashCode() : 0);
      result = result * 37 + (publisher_nick != null ? publisher_nick.hashCode() : 0);
      result = result * 37 + (publisher_subscribedCount != null ? publisher_subscribedCount.hashCode() : 0);
      result = result * 37 + (publisher_subscribed != null ? publisher_subscribed.hashCode() : 0);
      result = result * 37 + (publisher_defaultSelected != null ? publisher_defaultSelected.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SubscribePublisherPackage> {

    public String publisher_type;
    public String publisher_id;
    public String publisher_nick;
    public String publisher_subscribedCount;
    public Boolean publisher_subscribed;
    public Boolean publisher_defaultSelected;

    public Builder() {
    }

    public Builder(SubscribePublisherPackage message) {
      super(message);
      if (message == null) return;
      this.publisher_type = message.publisher_type;
      this.publisher_id = message.publisher_id;
      this.publisher_nick = message.publisher_nick;
      this.publisher_subscribedCount = message.publisher_subscribedCount;
      this.publisher_subscribed = message.publisher_subscribed;
      this.publisher_defaultSelected = message.publisher_defaultSelected;
    }

    public Builder publisher_type(String publisher_type) {
      this.publisher_type = publisher_type;
      return this;
    }

    public Builder publisher_id(String publisher_id) {
      this.publisher_id = publisher_id;
      return this;
    }

    public Builder publisher_nick(String publisher_nick) {
      this.publisher_nick = publisher_nick;
      return this;
    }

    public Builder publisher_subscribedCount(String publisher_subscribedCount) {
      this.publisher_subscribedCount = publisher_subscribedCount;
      return this;
    }

    public Builder publisher_subscribed(Boolean publisher_subscribed) {
      this.publisher_subscribed = publisher_subscribed;
      return this;
    }

    public Builder publisher_defaultSelected(Boolean publisher_defaultSelected) {
      this.publisher_defaultSelected = publisher_defaultSelected;
      return this;
    }

    @Override
    public SubscribePublisherPackage build() {
      return new SubscribePublisherPackage(this);
    }
  }
}
