// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class SystemEvent extends Message {

  public static final String DEFAULT_DEBUG = "";

  /**
   * 由不同业务定义的debug字符串
   */
  @ProtoField(tag = 1, type = STRING)
  public final String debug;

  /**
   * 各个业务自己的 package
   */
  @ProtoField(tag = 2)
  public final ExtraPackage extra_package;

  private SystemEvent(Builder builder) {
    super(builder);
    this.debug = builder.debug;
    this.extra_package = builder.extra_package;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SystemEvent)) return false;
    SystemEvent o = (SystemEvent) other;
    return equals(debug, o.debug)
        && equals(extra_package, o.extra_package);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = debug != null ? debug.hashCode() : 0;
      result = result * 37 + (extra_package != null ? extra_package.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SystemEvent> {

    public String debug;
    public ExtraPackage extra_package;

    public Builder() {
    }

    public Builder(SystemEvent message) {
      super(message);
      if (message == null) return;
      this.debug = message.debug;
      this.extra_package = message.extra_package;
    }

    /**
     * 由不同业务定义的debug字符串
     */
    public Builder debug(String debug) {
      this.debug = debug;
      return this;
    }

    /**
     * 各个业务自己的 package
     */
    public Builder extra_package(ExtraPackage extra_package) {
      this.extra_package = extra_package;
      return this;
    }

    @Override
    public SystemEvent build() {
      return new SystemEvent(this);
    }
  }
}
