// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class TabPackage extends Message {

  public static final String DEFAULT_NAME = "";
  public static final String DEFAULT_UNREAD_NUM = "";

  /**
   * tab 的命名
   */
  @ProtoField(tag = 1, type = STRING)
  public final String name;

  /**
   * 未读的数字
   */
  @ProtoField(tag = 2, type = STRING)
  public final String unread_num;

  private TabPackage(Builder builder) {
    super(builder);
    this.name = builder.name;
    this.unread_num = builder.unread_num;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TabPackage)) return false;
    TabPackage o = (TabPackage) other;
    return equals(name, o.name)
        && equals(unread_num, o.unread_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = name != null ? name.hashCode() : 0;
      result = result * 37 + (unread_num != null ? unread_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TabPackage> {

    public String name;
    public String unread_num;

    public Builder() {
    }

    public Builder(TabPackage message) {
      super(message);
      if (message == null) return;
      this.name = message.name;
      this.unread_num = message.unread_num;
    }

    /**
     * tab 的命名
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * 未读的数字
     */
    public Builder unread_num(String unread_num) {
      this.unread_num = unread_num;
      return this;
    }

    @Override
    public TabPackage build() {
      return new TabPackage(this);
    }
  }
}
