// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_transition.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 触发的信息
 */
public final class TriggerPackage extends Message {

  public static final String DEFAULT_TYPE = "";
  public static final String DEFAULT_SOURCE = "";

  /**
   * trigger的类型
   */
  @ProtoField(tag = 1, type = STRING)
  public final String type;

  /**
   * trigger source
   */
  @ProtoField(tag = 2, type = STRING)
  public final String source;

  private TriggerPackage(Builder builder) {
    super(builder);
    this.type = builder.type;
    this.source = builder.source;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TriggerPackage)) return false;
    TriggerPackage o = (TriggerPackage) other;
    return equals(type, o.type)
        && equals(source, o.source);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = type != null ? type.hashCode() : 0;
      result = result * 37 + (source != null ? source.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TriggerPackage> {

    public String type;
    public String source;

    public Builder() {
    }

    public Builder(TriggerPackage message) {
      super(message);
      if (message == null) return;
      this.type = message.type;
      this.source = message.source;
    }

    /**
     * trigger的类型
     */
    public Builder type(String type) {
      this.type = type;
      return this;
    }

    /**
     * trigger source
     */
    public Builder source(String source) {
      this.source = source;
      return this;
    }

    @Override
    public TriggerPackage build() {
      return new TriggerPackage(this);
    }
  }
}
