// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_event_package.proto
package com.wandoujia.logv3.model.packages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * Url信息
 */
public final class UrlPackage extends Message {

  public static final String DEFAULT_URL = "";
  public static final String DEFAULT_NORMALIZED_URL = "";
  public static final Vertical DEFAULT_VERTICAL = Vertical.OTHERS;

  /**
   * 链接，如"/detail/app?pn=com.wandoujia.roshan"
   */
  @ProtoField(tag = 1, type = STRING)
  public final String url;

  /**
   * 链接缩写，不包括细节，如"/detail/app?pn="
   */
  @ProtoField(tag = 2, type = STRING)
  public final String normalized_url;

  /**
   * 产品线，video,app,startpage...
   */
  @ProtoField(tag = 3, type = ENUM)
  public final Vertical vertical;

  private UrlPackage(Builder builder) {
    super(builder);
    this.url = builder.url;
    this.normalized_url = builder.normalized_url;
    this.vertical = builder.vertical;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UrlPackage)) return false;
    UrlPackage o = (UrlPackage) other;
    return equals(url, o.url)
        && equals(normalized_url, o.normalized_url)
        && equals(vertical, o.vertical);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = url != null ? url.hashCode() : 0;
      result = result * 37 + (normalized_url != null ? normalized_url.hashCode() : 0);
      result = result * 37 + (vertical != null ? vertical.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UrlPackage> {

    public String url;
    public String normalized_url;
    public Vertical vertical;

    public Builder() {
    }

    public Builder(UrlPackage message) {
      super(message);
      if (message == null) return;
      this.url = message.url;
      this.normalized_url = message.normalized_url;
      this.vertical = message.vertical;
    }

    /**
     * 链接，如"/detail/app?pn=com.wandoujia.roshan"
     */
    public Builder url(String url) {
      this.url = url;
      return this;
    }

    /**
     * 链接缩写，不包括细节，如"/detail/app?pn="
     */
    public Builder normalized_url(String normalized_url) {
      this.normalized_url = normalized_url;
      return this;
    }

    /**
     * 产品线，video,app,startpage...
     */
    public Builder vertical(Vertical vertical) {
      this.vertical = vertical;
      return this;
    }

    @Override
    public UrlPackage build() {
      return new UrlPackage(this);
    }
  }

  public enum Vertical
      implements ProtoEnum {
    OTHERS(0),
    /**
     * 其他
     */
    APP(1),
    /**
     * 应用
     */
    SEARCH(2),
    /**
     * 搜索
     */
    GAME(3),
    /**
     * 游戏
     */
    VIDEO(4),
    /**
     * 视频
     */
    MUSIC(5),
    /**
     * 音乐
     */
    WALLPAPER(6),
    /**
     * 壁纸
     */
    EBOOK(7),
    /**
     * 电子书
     */
    MYTHING(8),
    /**
     * my thing
     */
    SYNC(9),
    /**
     * 云同步
     */
    SETTING(10),
    /**
     * 设置
     */
    PLAYER(11),
    /**
     * 播放器
     */
    LAUNCHER(12),
    /**
     * launcher
     */
    STARTPAGE(13),
    /**
     * 首页
     */
    XIBAIBAI(14),
    /**
     * 洗白白
     */
    CLEAN(15),
    /**
     * 清理
     */
    SUBSCRIBE(16),
    /**
     * 订阅
     */
    COMMUNITY(17);

    private final int value;

    private Vertical(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
