/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wandoujia_base_utils_CipherUtil */

#ifndef _Included_com_wandoujia_base_utils_CipherUtil
#define _Included_com_wandoujia_base_utils_CipherUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wandoujia_base_utils_CipherUtil
 * Method:    getAESKey
 * Signature: (Landroid/content/Context;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wandoujia_base_utils_CipherUtil_getAESKeyNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_wandoujia_base_utils_CipherUtil
 * Method:    getAndroidId
 * Signature: (Landroid/content/Context;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wandoujia_base_utils_CipherUtil_getAndroidIdNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_wandoujia_base_utils_CipherUtil
 * Method:    getAuthKey
 * Signature: (Landroid/content/Context;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wandoujia_base_utils_CipherUtil_getAuthKeyNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
