// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./base.proto
package com.wandoujia.base.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.FLOAT;
import static com.squareup.wire.Message.Label.REPEATED;

public final class BaseFloats extends Message {

  public static final List<Float> DEFAULT_VAL = Collections.emptyList();

  @ProtoField(tag = 1, type = FLOAT, label = REPEATED)
  public final List<Float> val;

  private BaseFloats(Builder builder) {
    super(builder);
    this.val = immutableCopyOf(builder.val);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BaseFloats)) return false;
    return equals(val, ((BaseFloats) other).val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = val != null ? val.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<BaseFloats> {

    public List<Float> val;

    public Builder() {
    }

    public Builder(BaseFloats message) {
      super(message);
      if (message == null) return;
      this.val = copyOf(message.val);
    }

    public Builder val(List<Float> val) {
      this.val = val;
      return this;
    }

    @Override
    public BaseFloats build() {
      return new BaseFloats(this);
    }
  }
}
