// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./base.proto
package com.wandoujia.base.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class BaseLong extends Message {

  public static final Long DEFAULT_VAL = 0L;

  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long val;

  private BaseLong(Builder builder) {
    super(builder);
    this.val = builder.val;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BaseLong)) return false;
    return equals(val, ((BaseLong) other).val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = val != null ? val.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<BaseLong> {

    public Long val;

    public Builder() {
    }

    public Builder(BaseLong message) {
      super(message);
      if (message == null) return;
      this.val = message.val;
    }

    public Builder val(Long val) {
      this.val = val;
      return this;
    }

    @Override
    public BaseLong build() {
      checkRequiredFields();
      return new BaseLong(this);
    }
  }
}
