// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./base.proto
package com.wandoujia.base.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class BaseStrs extends Message {

  public static final List<String> DEFAULT_VAL = Collections.emptyList();

  @ProtoField(tag = 1, type = STRING, label = REPEATED)
  public final List<String> val;

  private BaseStrs(Builder builder) {
    super(builder);
    this.val = immutableCopyOf(builder.val);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BaseStrs)) return false;
    return equals(val, ((BaseStrs) other).val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = val != null ? val.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<BaseStrs> {

    public List<String> val;

    public Builder() {
    }

    public Builder(BaseStrs message) {
      super(message);
      if (message == null) return;
      this.val = copyOf(message.val);
    }

    public Builder val(List<String> val) {
      this.val = val;
      return this;
    }

    @Override
    public BaseStrs build() {
      return new BaseStrs(this);
    }
  }
}
