// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./base.proto
package com.wandoujia.base.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class BaseStr extends Message {

  public static final String DEFAULT_VAL = "";

  @ProtoField(tag = 1, type = STRING)
  public final String val;

  private BaseStr(Builder builder) {
    super(builder);
    this.val = builder.val;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BaseStr)) return false;
    return equals(val, ((BaseStr) other).val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = val != null ? val.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<BaseStr> {

    public String val;

    public Builder() {
    }

    public Builder(BaseStr message) {
      super(message);
      if (message == null) return;
      this.val = message.val;
    }

    public Builder val(String val) {
      this.val = val;
      return this;
    }

    @Override
    public BaseStr build() {
      return new BaseStr(this);
    }
  }
}
