// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./base.proto
package com.wandoujia.base.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class BaseInt extends Message {

  public static final Integer DEFAULT_VAL = 0;

  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer val;

  private BaseInt(Builder builder) {
    super(builder);
    this.val = builder.val;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BaseInt)) return false;
    return equals(val, ((BaseInt) other).val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = val != null ? val.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<BaseInt> {

    public Integer val;

    public Builder() {
    }

    public Builder(BaseInt message) {
      super(message);
      if (message == null) return;
      this.val = message.val;
    }

    public Builder val(Integer val) {
      this.val = val;
      return this;
    }

    @Override
    public BaseInt build() {
      checkRequiredFields();
      return new BaseInt(this);
    }
  }
}
