// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./base.proto
package com.wandoujia.base.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class BaseBoolean extends Message {

  public static final Boolean DEFAULT_VAL = false;

  @ProtoField(tag = 1, type = BOOL, label = REQUIRED)
  public final Boolean val;

  private BaseBoolean(Builder builder) {
    super(builder);
    this.val = builder.val;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BaseBoolean)) return false;
    return equals(val, ((BaseBoolean) other).val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = val != null ? val.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<BaseBoolean> {

    public Boolean val;

    public Builder() {
    }

    public Builder(BaseBoolean message) {
      super(message);
      if (message == null) return;
      this.val = message.val;
    }

    public Builder val(Boolean val) {
      this.val = val;
      return this;
    }

    @Override
    public BaseBoolean build() {
      checkRequiredFields();
      return new BaseBoolean(this);
    }
  }
}
