// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./base.proto
package com.wandoujia.base.models;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.FLOAT;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class BaseFloat extends Message {

  public static final Float DEFAULT_VAL = 0F;

  @ProtoField(tag = 1, type = FLOAT, label = REQUIRED)
  public final Float val;

  private BaseFloat(Builder builder) {
    super(builder);
    this.val = builder.val;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BaseFloat)) return false;
    return equals(val, ((BaseFloat) other).val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = val != null ? val.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<BaseFloat> {

    public Float val;

    public Builder() {
    }

    public Builder(BaseFloat message) {
      super(message);
      if (message == null) return;
      this.val = message.val;
    }

    public Builder val(Float val) {
      this.val = val;
      return this;
    }

    @Override
    public BaseFloat build() {
      checkRequiredFields();
      return new BaseFloat(this);
    }
  }
}
