// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./base.proto
package com.wandoujia.base.models;

import com.squareup.wire.ByteString;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PNG extends Message {

  public static final ByteString DEFAULT_CONTENT = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString content;

  private PNG(Builder builder) {
    super(builder);
    this.content = builder.content;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PNG)) return false;
    return equals(content, ((PNG) other).content);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = content != null ? content.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<PNG> {

    public ByteString content;

    public Builder() {
    }

    public Builder(PNG message) {
      super(message);
      if (message == null) return;
      this.content = message.content;
    }

    public Builder content(ByteString content) {
      this.content = content;
      return this;
    }

    @Override
    public PNG build() {
      checkRequiredFields();
      return new PNG(this);
    }
  }
}
