// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./log_model.proto
package com.wandoujia.log.toolkit.model;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class LaunchPackage extends Message {

  public static final String DEFAULT_ACTION = "";
  public static final String DEFAULT_ACTIVITY = "";
  public static final String DEFAULT_DATA = "";
  public static final String DEFAULT_REASON = "";

  @ProtoField(tag = 1)
  public final LaunchSourcePackage sourcePackage;

  @ProtoField(tag = 2, type = STRING)
  public final String action;

  @ProtoField(tag = 3, type = STRING)
  public final String activity;

  @ProtoField(tag = 4, type = STRING)
  public final String data;

  @ProtoField(tag = 5, type = STRING)
  public final String reason;

  private LaunchPackage(Builder builder) {
    super(builder);
    this.sourcePackage = builder.sourcePackage;
    this.action = builder.action;
    this.activity = builder.activity;
    this.data = builder.data;
    this.reason = builder.reason;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LaunchPackage)) return false;
    LaunchPackage o = (LaunchPackage) other;
    return equals(sourcePackage, o.sourcePackage)
        && equals(action, o.action)
        && equals(activity, o.activity)
        && equals(data, o.data)
        && equals(reason, o.reason);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = sourcePackage != null ? sourcePackage.hashCode() : 0;
      result = result * 37 + (action != null ? action.hashCode() : 0);
      result = result * 37 + (activity != null ? activity.hashCode() : 0);
      result = result * 37 + (data != null ? data.hashCode() : 0);
      result = result * 37 + (reason != null ? reason.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LaunchPackage> {

    public LaunchSourcePackage sourcePackage;
    public String action;
    public String activity;
    public String data;
    public String reason;

    public Builder() {
    }

    public Builder(LaunchPackage message) {
      super(message);
      if (message == null) return;
      this.sourcePackage = message.sourcePackage;
      this.action = message.action;
      this.activity = message.activity;
      this.data = message.data;
      this.reason = message.reason;
    }

    public Builder sourcePackage(LaunchSourcePackage sourcePackage) {
      this.sourcePackage = sourcePackage;
      return this;
    }

    public Builder action(String action) {
      this.action = action;
      return this;
    }

    public Builder activity(String activity) {
      this.activity = activity;
      return this;
    }

    public Builder data(String data) {
      this.data = data;
      return this;
    }

    public Builder reason(String reason) {
      this.reason = reason;
      return this;
    }

    @Override
    public LaunchPackage build() {
      return new LaunchPackage(this);
    }
  }
}
